docs/meetings/community/06.md, docs/meetings/community/write-ups/cm06/oliver.md
=> Add write-up for CM06

docs/meetings/community/write-ups/cm06/luke.md
=> added CM06 writeup: luke

docs/meetings/community/write-ups/cm06/jorge.md
=> Add write-up for CM06: jorge

docs/meetings/community/06.md, docs/meetings/community/write-ups/cm06/brett.md
=> Add write-up for CM06: Brett

docs/dev/aragon-core_home.md
=> Change a broken link on aragon-core_home

docs/index.md
=> Add missing sections to the summary of contents

docs/dev/AragonOS.md
Closes #43 
Removing complicated logic feels so good.
=> Update aragonOS doc to reflect aragon/aragon-core#155 changes

docs/design/index.md
There is a bunch of stuff in this page that isn't branding.
=> Fix design header copy

docs/meetings/community/write-ups/cm07/luis.md
=> Add a Write-Up for December 2017

docs/jobs/openings/frontend.md
You should also consider updating [this page](https://github.com/aragon/aragon-wiki/blob/master/docs/dev/index.md#aragon-ui), with more recent informations.
cc @bpierre
=> Frontend job requirements are React, not Vue

docs/spanish/index.md, docs/translations/spanish/index.md, mkdocs.yml
=> Spanish internationalization scaffolding

docs/meetings/community/write-ups/cm07/luke.md
=> added writeup for cm07

docs/meetings/community/07.md, docs/meetings/community/write-ups/cm07/pierre.md, mkdocs.yml
=> Write-up for CM07: Pierre

docs/dev/AragonOS.md
=> Revert "AragonOS grammar and style changes"

docs/translations/spanish/aragonos.md
Translation of the AragonOS document based on commits in #95. I have tried to minimise my own biases in the translation.
Thank you for your work, it is a pleasure to contribute to this amazing project!
Cheers,
Alejo Rodríguez 
Fixes #87
=> Translate AragonOS doc to Spanish Fixes #87

docs/videos/community.md
=> Add Community Meeting 07 links

docs/blog/2018.md
=> Create 2018 blog directory and add latest posts

docs/documentation/Code_of_Conduct.md
Minor grammar fixes, formatting, added prohibitions on organizing pump-and-dumps and sharing illegal links
=> Update Code of Conduct

docs/index.md
Closes #38 
(Sorry to bundle multiple edits in one PR - if you need me to separate these changes into multiple PRs let me know)
=> Fix formatting, grammar, add section for Community Channels

docs/press/media-mentions.md
Add `Audio Interviews` section, FLOSS Weekly ep, An Ethereum Podcast ep, The Boost VC Podcast ep.
Closes #125
=> Update media mentions

docs/nest/guides/guide_for_submitting_a_proposal_for_grants.md, docs/nest/guides/guide_for_submitting_a_request_for_funding.md, docs/nest/index.md, docs/nest/templates/ISSUE_TEMPLATE.md, docs/nest/templates/PULL_REQUEST_TEMPLATE.md, docs/nest/templates/roadmap.md, docs/nest/templates/team.md, mkdocs.yml
=> Add Nest section

docs/blog/2018.md
Added posts about the Nest launch and aragonOS 3.0 release
Closes #144
=> Update 2018 blog index

docs/meetings/community/write-ups/cm08/luis.md
=> Added my write up for cm08, closes #134

docs/meetings/community/write-ups/cm08/jorge.md, mkdocs.yml
=> Cm08 jorge

docs/meetings/community/write-ups/cm08/tatu.md
=> Community Meeting 08 Write-Up - Tatu

docs/meetings/community/write-ups/cm08/brett.md
=> Add write-up for CM08: Brett

docs/blog/2018.md
=> Added blog posts for Feb 2018 thru current day

docs/meetings/community/write-ups/cm09/pierre.md
Closes https://github.com/aragon/aragon-wiki/issues/163
=> Add Pierre cm09 write-up

docs/meetings/community/write-ups/cm09/bingen.md
=> Add write-up for CM09: ßingen

docs/meetings/community/write-ups/cm09/luke.md
For February community meeting. Closes #168
=> Addes luke.md

docs/meetings/community/write-ups/cm09/maria.md
=> Add write-up for CM09: Maria

docs/meetings/community/write-ups/cm09/oliver.md
=> Add writeup for CM09

docs/meetings/community/write-ups/cm09/jorge.md
=> Add Jorge cm09 write-up

docs/meetings/community/write-ups/cm09/jouni.md, mkdocs.yml
=> Add a Write-Up for February 2018 - Jouni

docs/meetings/community/write-ups/cm10/bingen.md, mkdocs.yml
=> Add write-up for CM10: ßingen

docs/meetings/community/write-ups/cm10/oliver.md
=> Add CM10 write up for Oliver

docs/meetings/community/write-ups/cm10/luke.md
=> Added writeup for Luke

docs/meetings/community/write-ups/cm10/maria.md
=> Add CM10 write-up for Maria

docs/meetings/community/write-ups/cm10/tatu.md
=> add tatucm10 write-up

docs/meetings/community/write-ups/cm10/luis.md
=> Adding writeup for cm10

docs/meetings/community/write-ups/cm10/pierre.md
=> Add Pierre cm10 write-up

docs/meetings/community/write-ups/cm10/brett.md
=> Add write-up for CM10: Brett

docs/meetings/community/write-ups/cm11/luis.md
=> Closes #251

docs/meetings/community/write-ups/cm11/jorge.md
=> Add jorge cm11 write-up

docs/meetings/community/write-ups/cm11/bingen.md
=> Cm11 bingen

docs/meetings/community/write-ups/cm11/pierre.md
Closes https://github.com/aragon/aragon-wiki/issues/245
=> Add Pierre cm11 write-up

docs/jobs/openings/solidity.md
Discussed a few months ago, but this updates our solidity job opening to a new, more generic challenge given we now maintain a payroll app.
=> Update solidity.md to create an Aragon App instead

docs/documentation/multisigs/community.md
=> Added myself to the documentation

docs/documentation/legal/CLA.md, docs/documentation/legal/Licenses.md, docs/documentation/legal/Terms_of_use_websites.md, docs/documentation/legal/Trademark_policy.md, mkdocs.yml
In order to deprecate https://github.com/aragon/legal
=> Added all legal docs

docs/jobs/openings/web.md
"Wizard" is a male figure but people of any gender should feel comfortable applying to this role.
=> Remove gendered language from job listing

docs/jobs/openings/frontend.md
"Wizard" is a male figure but people of any gender should feel comfortable applying to this role.
=> Remove gendered language

docs/press/media-mentions.md
There is already a section for video interviews here: https://wiki.aragon.org/videos/interviews/
=> Remove video interviews

docs/videos/dev.md, docs/videos/template.md, mkdocs.yml
=> Add All Core Devs section to mkdocs.yml

docs/design/artwork/ANT/.directory, docs/design/artwork/basic/.directory, docs/documentation/manifesto.md, mkdocs.yml
=> Add Manifesto to wiki

docs/videos/interviews.md, docs/videos/presentations.md
Need to add @luisivan's slides from the Web3 Summit presentation.
=> Add Web3 videos

docs/press/media-mentions.md
Also rearranged interviews by date
=> Add Decentralize This! interview

docs/documentation/aragon_network_token.md
Liqui is shutting down, see announcement at https://liqui.io/
=> Removing Liqui

docs/projects/index.md
- Created an Aragon Statistics section
- Alphabetized list
=> Add BOTI, Ocean to projects page

README.md
Fixes #107 
Honestly, I just wanna close the issue :D
=> TravisCI automatically does this now.

docs/documentation/aragon_network_token.md
- I was told by a trader who contacted Cumberland that they said they do not trade ANT
=> Remove Cumberland from Trade ANT - OTC Brokers section

docs/projects/index.md
- Remove daolist.io (inactive) and Aragon DAC (inactive)
- Add MyBit, Pool Together, Video DAC
=> Update Third Party Projects page

docs/documentation/governance.md
- Add ANV-4 info
- Add approved AGPs from ANV-3
=> Update Governance overview page

docs/working-groups/meeting-notes/strategy-wg/Strategycall20190913.md, docs/working-groups/meeting-notes/strategy-wg/Strategycall20190927.md
Adding notes for strategy call #6 and #7
=> strategy call notes

docs/about/history.md, docs/media/press/press-kit.md, docs/network/governance/how_to_vote.md, mkdocs.yml
=> Fix on images and two broken sidebar links

docs/working-groups/overview.md, docs/working-groups/registry.md
Moves the "suggested" working groups that don't yet exist to a "proposed" section.
=> Clean up documentation of working groups

docs/network/aragon_network_token.md
- Add AGP-1 and AGP-10 info
- Add Aragon Court info
- Add Aragon Chain info
- Update Bittrex listing info
=> Update Aragon Network Token documentation

mkdocs.yml
=> Add link to transparency page

docs/all_aragon_devs/meeting_notes/alldevs20191125.md, docs/all_aragon_devs/overview.md, mkdocs.yml
uploading notes of all devs #36 and agenda for all devs #37
=> All Devs #36 notes

docs/all_aragon_devs/meeting_notes/alldevs20191223.md, docs/all_aragon_devs/overview.md, mkdocs.yml
- All Devs #38 notes
- All Devs #39 agenda
=> Alldevs #38

docs/all_aragon_devs/meeting_notes/alldevs20200106.md, docs/all_aragon_devs/overview.md, mkdocs.yml
- All Devs 39 notes
- All Devs 40 agenda
- Fix December link names
=> All devs notes 39

docs/network/aragon_network_token.md
- Announcement: https://blog.kyber.network/aragon-ant-is-now-available-on-kyber-network-9bf094fd7f91
=> Add KyberSwap to Aragon Network Token documentation

docs/javascript/extra_js.js
Updates the tracking script since it changed during a version migration of Matomo.
=> Fix Matomo

docs/all_aragon_devs/meeting_notes/alldevs20200120.md, docs/all_aragon_devs/overview.md, mkdocs.yml
- All Devs 40 notes
- All Devs 41 agenda
=> All devs notes 40

docs/all_aragon_devs/meeting_notes/alldevs20200217.md, docs/all_aragon_devs/overview.md, mkdocs.yml
- Add All Aragon Devs 42 notes
- Update menu and overview
- Remove Louis contact
=> All Aragon Devs 42

docs/network/aragon_network_token.md
Swapzone finds, aggregates and indicates the most relevant exchange deals on the crypto market.
=> Add Swapzone - exchange aggregator

docs/all_aragon_devs/meeting_notes/alldevs20200302.md, docs/all_aragon_devs/overview.md, mkdocs.yml
- Add All Aragon Devs 43 notes
- Update menu and overview
=> All Aragon Devs 43

docs/association/security/an_bug_bounty.md, docs/association/security/client_bug_bounty.md, mkdocs.yml
=> Security: add Dandelion organizations to client bug bounty

docs/association/legal/Privacy_policy.md
As per the new version prepared by Jose Nuno
=> Update privacy policy

mkdocs.yml
=> Archive documentation

docs/about/projects.md
- https://mainnet.aragon.org/#elimuai
=> Added links for the elimu.ai Community DAO

docs/association/multisigs/community.md
=> Add Stefano and Brayton to the community multisig

docs/network/aragon_network_token.md
- Also removed reference to Aragon Chain, since that's [no longer happening](https://aragon.org/blog/sunsetting-aragon-chain).
=> Add info about ANTv2
